# Generated by Django 2.0.9 on 2019-05-31 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveSmallIntegerField(choices=[(0, 'Want to Evaluate'), (1, 'Neutral'), (2, 'Refuse to Evaluate')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.CharField(max_length=255, unique=True)),
                ('info', models.CharField(max_length=4096)),
                ('start_date', models.DateField()),
                ('abstract_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('presentation_date', models.DateField()),
                ('end_date', models.DateField()),
                ('evaluated', models.BooleanField(default=False)),
                ('chairedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, 'Not Graded'), (1, 'Strong Accept'), (2, 'Accept'), (3, 'Weak Accept'), (4, 'Borderline'), (5, 'Weak Reject'), (6, 'Reject'), (7, 'Strong Reject')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PcMemberIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Actor')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, 'Not Graded'), (1, 'Strong Accept'), (2, 'Accept'), (3, 'Weak Accept'), (4, 'Borderline'), (5, 'Weak Reject'), (6, 'Reject'), (7, 'Strong Reject')], default=1)),
                ('pcmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.PcMemberIn')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.CharField(max_length=2550)),
                ('full_paper', models.CharField(max_length=25500, null=True)),
                ('meta_info', models.CharField(max_length=10000, null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('pcmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.PcMemberIn')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Submission')),
            ],
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Submission'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conferences.Submission'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='pcmember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.PcMemberIn'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Submission'),
        ),
    ]
