# Generated by Django 2.0.9 on 2019-05-29 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.CharField(max_length=255, unique=True)),
                ('info', models.CharField(max_length=4096)),
                ('startDate', models.DateField()),
                ('abstractDate', models.DateField()),
                ('submissionDate', models.DateField()),
                ('presentationDate', models.DateField()),
                ('endDate', models.DateField()),
                ('chairedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Actor')),
            ],
        ),
    ]
