# Generated by Django 2.0.9 on 2019-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
