# Generated by Django 2.0.9 on 2019-05-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcMemberIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Actor')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='fullPaper',
            field=models.CharField(max_length=25500, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='metaInfo',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
