# Generated by Django 2.0.9 on 2019-06-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='sections',
            field=models.ManyToManyField(to='conferences.Section'),
        ),
        migrations.AddField(
            model_name='submission',
            name='chosen_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='conferences.Section'),
            preserve_default=False,
        ),
    ]
