# Generated by Django 2.0.9 on 2019-05-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20190529_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference'),
            preserve_default=False,
        ),
    ]
