# Generated by Django 2.0.9 on 2019-05-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_submission_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(choices=[(0, 'Want to Evaluate'), (1, 'Neutral'), (2, 'Refuse to Evaluate')], max_length=1)),
                ('pcmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.PcMemberIn')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('pcmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.PcMemberIn')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Submission')),
            ],
        ),
    ]
