# Generated by Django 2.0.9 on 2019-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_auto_20190530_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Want to Evaluate'), (1, 'Neutral'), (2, 'Refuse to Evaluate')], default=1),
        ),
    ]
