# Generated by Django 2.0.9 on 2019-06-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_submission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='chosen_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='conferences.Section'),
        ),
    ]
