# Generated by Django 2.0.9 on 2019-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20190603_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.FileField(upload_to='abstracts'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='full_paper',
            field=models.FileField(null=True, upload_to='full-papers'),
        ),
    ]
