# Generated by Django 2.0.9 on 2019-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20190530_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default='default title', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.CharField(max_length=2550),
        ),
    ]
