# Generated by Django 2.0.9 on 2019-05-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_auto_20190531_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, 'Not Graded'), (1, 'Strong Accept'), (2, 'Accept'), (3, 'Weak Accept'), (4, 'Borderline'), (5, 'Weak Reject'), (6, 'Reject'), (7, 'Strong Reject')], default=1)),
                ('pcmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.PcMemberIn')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Submission')),
            ],
        ),
    ]
