# Generated by Django 2.0.9 on 2019-06-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_auto_20190604_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Actor')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Submission')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='session_chair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Actor'),
        ),
    ]
