# Generated by Django 2.0.9 on 2019-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_reviewassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='abstractDate',
            new_name='abstract_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='presentationDate',
            new_name='presentation_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='submissionDate',
            new_name='submission_date',
        ),
        migrations.AlterField(
            model_name='submission',
            name='full_paper',
            field=models.CharField(max_length=25500, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='meta_info',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
