run:
	-@clear
	-@python3 manage.py runserver

mkmigration:
	-@clear
	-@python3 manage.py makemigrations conferences

migrate:
	-@clear
	-@python3 manage.py migrate

shell:
	-@clear
	-@python3 manage.py shell

.PHONY: run migrate mkmigration shell
